#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

PROG="cfnat"

start_service() {
    config_load "cfnat"
    
    local enabled
    config_get_bool enabled "main" "enabled" "0"
    [ "$enabled" -eq "1" ] || return 0
    
    local bindir workdir
    config_get bindir "main" "bindir" "/usr/bin"
    config_get workdir "main" "workdir" "/etc/nanoswift/run"

    PROG="${bindir}/${PROG}"
    
    [ -x "$PROG" ] || {
        logger -t "cfnat" "ERROR: $PROG not executable"
        return 1
    }
    
    mkdir -p "$workdir" 2>/dev/null
    
    procd_open_instance
    procd_set_param command "$PROG"

    procd_append_param command "-D" "$workdir"

    local val
    config_get val "main" "addr" "127.0.0.1:2345"
    procd_append_param command "-addr" "$val"

    config_get val "main" "colo" ""
    [ -n "$val" ] && {
        procd_append_param command "-colo" "$val"
    }

    config_get val "main" "delay" "300"
    procd_append_param command "-delay" "$val"

    config_get val "main" "ipnum" "20"
    procd_append_param command "-ipnum" "$val"

    config_get val "main" "ips" "4"
    procd_append_param command "-ips" "$val"

    config_get val "main" "ipstart" ""
    [ -n "$val" ] && {
        procd_append_param command "-ipstart" "$val"
    }

    config_get val "main" "log_level" "info"
    procd_append_param command "-log" "$val"

    config_get val "main" "num" "5"
    procd_append_param command "-num" "$val"

    config_get val "main" "port" "443"
    procd_append_param command "-port" "$val"

    config_get val "main" "http_port" "80"
    procd_append_param command "-http-port" "$val"

    local random_val
    config_get_bool random_val "main" "random" "1"
    procd_append_param command "-random" "$random_val"

    config_get val "main" "task" "500"
    procd_append_param command "-task" "$val"
    
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile "/var/run/${PROG##*/}.pid"
    
    procd_close_instance
    
    logger -t "cfnat" "Starting cfnat"
}

service_triggers() {
    procd_add_reload_trigger "cfnat"
}

stop_service() {
    logger -t "cfnat" "Stopping..."
}